# Copyright (C) 2016 Christopher Arndt <chris@chrisarndt.de>

BINARY = midi_encoder

OBJS = hd44780.o rotary_encoder.o sleep.o

OPENCM3_DIR=../libopencm3
LDSCRIPT = ../stm32f4-discovery.ld

include ../libopencm3.target.mk
